version: '3'

services:
    database:
        build:
            context: ./docker/postgres
        ports:
          - "${DB_DOCKER_HOST_PORT}:5432"
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - postgresql:/var/lib/postgresql/data/

    php:
        build:
            context: ./docker/php
        depends_on:
          - database
        working_dir: /app
        volumes:
            - ./:/app/
            - ~/.composer/docker-cache/:/root/.composer:cached

    rabbitmq:
      build:
        context: ./docker/rabbitmq
      ports:
        - "${RABBIT_MQ_PORT}:15672"
      hostname: rabbitmq
      restart: always
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
        - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
          #    webserver:
#        build:
#          context: ./docker/nginx/
#        depends_on:
#          - js
#          - php
#        ports:
#          - "${APP_DOCKER_HOST_PORT}:80"
#        tty: true
#        volumes:
#            - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:ro
#            - ./public/:/app/public/:ro


volumes:
  postgresql:
    driver: local
